{% set version = "0.24.1" %}
{% set minimum_core = "0.20.0" %}

package:
  name: compass-interface
  version: {{ version }}

source:
  url: https://github.com/the-scouts/compass-interface/releases/download/v{{ version }}/compass-interface-{{ version }}.tar.gz
  sha256: 4bc2085c29ac8645fd859c1a0cbcd51f0216f6ec260da42aaac49e89b8dda807

build:
  number: 9

outputs:
  # omni package
  - name: compass-interface
    build:
      noarch: python
    requirements:
      host:
        - python >=3.9
      run:
        - {{ pin_subpackage('compass-interface-http', exact=True) }}
        - {{ pin_subpackage('compass-interface-pandas', exact=True) }}
    test:
      imports:
        - compass
        - compass.core
#    about:
#      description:

  # web api package
  - name: compass-interface-http
    build:
      noarch: python
      script: python -m pip install . --no-deps --ignore-installed -vv
    requirements:
      host:
        - python >=3.9
        - pip
      run:
        - python >=3.9
        - compass-interface-core >={{ minimum_core }}
        - fastapi
        - cryptography
        - python-jose
        - python-multipart
    test:
      imports:
        - compass
        - compass.core

    # tabluar interface package
    - name: compass-interface-pandas
      build:
        noarch: python
        script: python -m pip install . --no-deps --ignore-installed -vv
      requirements:
        host:
          - python >=3.9
          - pip
        run:
          - python >=3.9
          - compass-interface-core >={{ minimum_core }}
          - pandas
          - pyarrow
      test:
        imports:
          - compass
          - compass.core

about:
  home: https://github.com/the-scouts/compass-interface
  license: MIT
  license_file: LICENSE
  summary: The unofficial API to the TSA Compass membership database
#  description: |
#    longer description
  dev_url: https://github.com/the-scouts/compass-interface
#  doc_url: 

extra:
  recipe-maintainers:
    - AA-Turner
