{% set version = "0.24.1" %}

package:
  name: compass-interface
  version: {{ version }}

source:
  url: https://github.com/the-scouts/compass-interface/releases/download/v{{ version }}/compass-interface-{{ version }}.tar.gz
  sha256: 4bc2085c29ac8645fd859c1a0cbcd51f0216f6ec260da42aaac49e89b8dda807

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - compass-interface-core >=0.20.0

test:
  imports:
    - compass
    - compass.core

outputs:
  # base package (just core)
  - name: compass-interface-base
  
  # web api package
  - name: compass-interface-http
    requirements:
      host:
        - python
      run:
        - {{ pin_subpackage('compass-interface-base', exact=True) }}
        - fastapi
        - cryptography
        - python-jose
        - python-multipart

  # tabluar interface package
  - name: compass-interface-pandas
    requirements:
      host:
        - python
      run:
        - {{ pin_subpackage('compass-interface-base', exact=True) }}
        - pandas
        - pyarrow

  # omni package
  - name: compass-interface
    requirements:
      host:
        - python
      run:
        - {{ pin_subpackage('compass-interface-base', exact=True) }}
        - {{ pin_subpackage('compass-interface-http', exact=True) }}
        - {{ pin_subpackage('compass-interface-pandas', exact=True) }}

about:
  home: https://github.com/the-scouts/compass-interface
  license: MIT
  license_file: LICENSE
  summary: The unofficial API to the TSA Compass membership database
  dev_url: https://github.com/the-scouts/compass-interface

extra:
  recipe-maintainers:
    - AA-Turner
