{% set version = "0.22.9" %}

package:
  name: compass-interface
  version: {{ version }}

source:
  url: https://github.com/the-scouts/compass-interface/releases/download/v{{ version }}/compass-interface-{{ version }}.tar.gz
  sha256: 721f30a371492b20d4419359fc7935d182b4c0f0fc38ae2755bd52a685eb7a6b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - compass-interface-core >=0.8.0
    - pandas
    - pyarrow
    - fastapi
    - python-jose
    - aioredis
    - python-multipart

test:
  imports:
    - compass

about:
  home: https://github.com/the-scouts/compass-interface
  license: MIT
  license_file: LICENSE
  summary: The unofficial API to the TSA Compass membership database
  dev_url: https://github.com/the-scouts/compass-interface

extra:
  recipe-maintainers:
    - AA-Turner
